### ISSUE TITLE
How to parse string to Date type?

### ISSUE THREAD

**Issue by jeremiasdsa** [gcharita/XMLMapper#11]
Hi @gcharita,

How can I parse a string to Date type?

ex:  <Date>"2018-04-30T22:19:31 CEST"</Date>

**Comment by gcharita** [comment]
Hi. If you can find a `DateFormatter` that can convert your string value to the corresponding `Date`, you can use `XMLDateFormatterTransform`.
For example to map the following `XML`:

```xml
<Response>
    <date>2018-04-30T22:19:31</date>
</Response>
```

You can use:

```swift
class Response: XMLMappable {
    var nodeName: String!
    
    var date: Date?
    
    required init(map: XMLMap) {
        
    }
    
    func mapping(map: XMLMap) {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
        date <- (map["date"], XMLDateFormatterTransform(dateFormatter: dateFormatter))
    }
}
```

Just replace the `dateFormatter`, in the `mapping(map:)` function, with yours.
