### ISSUE TITLE
Serialization for CDATA wrapped values

### ISSUE THREAD

**Issue by pazone** [gcharita/XMLMapper#14]
CDATA deserialization works great out of the box. It would be great to create some approach to serialize CDATA wrapped values. 

For example:
```
class MyData: XMLMappable {
    var nodeName: String!
    var cdataValue: String?
    ...
    func mapping(map: XMLMap) {
        cdataValue <- map.attributes["cdataValue"]
    }
}
```
```
let myData = MyData()
myData.cdataValue = "actualValue"
print(myData.toXMLString())
```

```
<cdataValue><![CDATA[ actualValue ]]></cdataValue>
```

**Comment by gcharita** [comment]
This is a good addition-enhancement. Thank you.

Trying to think of a solution, a custom `XMLTransformType` will not actually achieve this.

So, the only proposal that could work is to parse CDATA wrapped values as `Data` objects.
But this will have an impact on `XMLMappable` struct-classes, because `Data` objects cannot mapped in `String` properties directly. There have to use a custom `XMLTransformType`.

Also, another thing that we have to consider is that an XML tag can have more than one CDATA wrapped values. There we have to use array of `Data` objects.

I will try to implement this. Any other suggestions are welcome.

**Comment by pazone** [comment]
Here is one of my very stupid approaches. 
``` 
class CDATATransformType: XMLTransformType {
    public typealias Object = String
    public typealias XML = String
    
    public init() {}
    
    open func transformFromXML(_ value: Any?) -> String? {
        guard let string = value as? String else {
            return nil
        }
        return string
    }
    
    open func transformToXML(_ value: String?) -> String? {
        guard let data = value else {
            return nil
        }
        return "<![CDATA[ \(data) ]]>"
    }   
}
```
It works only for such mapping(when innerText is wrapped with CDATA): 
```
SingleCDATA: XMLMappable {
    var nodeName: String!
    var value: String?
      
    func mapping(map: XMLMap) {
        value <- (map.innerText, CDATATransformType())
    }
    
}
```
For some reasons `<` and `>` in CDATA are not being escaped in this particular case. Probably it is a bug but it allows to overcome the problem. 
So the result looks ok 
```<myElement><![CDATA[ value ]]</myElement>```

In the next example `<![CDATA` string will be escaped(field value is wrapped): 
```
CDATAAsField: XMLMappable {
    var nodeName: String!
    var value: String?
      
    func mapping(map: XMLMap) {
        value <- (map["value"], CDATATransformType())
    }
    
}
```

the result is: 
```
<myElement>
    <value>&ltl![CDATA[ value ]]&gt;</value>
</myElement>
```
It is not very suitable result because after deserialization our `value` turns to `&ltl![CDATA[ value ]]&gt;`

**Comment by pazone** [comment]
So to my mind the main problem is how to tell to mapper should it wrap particular field value to `cdata` or leave it bare.

**Comment by gcharita** [comment]
Exactly. This is the reason why a custom `XMLTransformType` doesn't work.

Given the fact that a simple `String` cannot tell the `XMLMapper` how to map itself (leave it bare or XML encode) again the `Data` object approach seems to be the only solution. Of course it requires the releasing of a new version.

I will try it in a new branch to see if it works.

**Comment by gcharita** [comment]
@pazone sorry for the late answer.

I made an implementation that solves this issue in `enhancement/cdata-mapping`  branch. You can try it by adding the following line to your `Podfile`:

```ruby
pod 'XMLMapper', :git => 'https://github.com/gcharita/XMLMapper.git', :branch => 'enhancement/cdata-mapping'
```

In this branch the CDATA wrapper values are mapped originally in `Array<Data>` type. With that way I can now track the type and sterilize it differently. (in `<![CDATA[ ]]>`)

But if you want to map the CDATA wrapped values into `String` type, you have to use the new build it `XMLCDATATransform` like that:

```swift
class TestCDATAMappable: XMLMappable {
    var nodeName: String!
    
    var testCDATA: String?
    
    required init(map: XMLMap) { }
    
    func mapping(map: XMLMap) {
        testCDATA <- (map["testCDATA"], XMLCDATATransform())
    }
}
```
or provide your own implementation by creating a custom `XMLTransformType`.

Try it out and let me know if you think it's ok.

The opinions of the library users are really important in this discussion. Thank you.

**Comment by pazone** [comment]
Thanks a lot! I'm going to check it asap

**Comment by martinho13** [comment]
### <elements>
	<element lang="en_US">
		<![CDATA[ Hello world ]]>
	</element>
	<element lang="zh_TW">
		<![CDATA[  value 2  ]]>
	</element>
	<element lang="zh_CN">
		<![CDATA[ value 3 ]]>
	</element>
</elements>

how can i map the CDATA ?

element <- (map["element"], XMLCDATATransform())

it cannot map the value

**Comment by gcharita** [comment]
@martinho13 you are right.

To map CDATA value of `element` you have to use another `XMLMappable` model class. (because of the existence of the `lang` attribute)

An example model to map your sample XML is the following:

```swift
class Root: XMLMappable {
    var nodeName: String!

    var elements: [Element]?
    
    required init(map: XMLMap) { }
    
    func mapping(map: XMLMap) {
        elements <- map["element"]
    }
}

class Element: XMLMappable {
    var nodeName: String!
    
    var lang: String?
    var innerCDATA: String?
    
    required init(map: XMLMap) { }
    
    func mapping(map: XMLMap) {
        lang <- map.attributes["lang"]
        innerCDATA <- (map.innerCDATA, XMLCDATATransform())
    }
}
```

Sorry for possible errors in the code (I cannot test it right now)

**Comment by martinho13** [comment]
I tried it work thanks
