### ISSUE TITLE
Invalid redeclaration of '<-' error in Xcode 10

### ISSUE THREAD

**Issue by joseph-517** [gcharita/XMLMapper#16]
Everything was working fine in xcode 9.4. After updating to xcode 10, the below errors started appearing.

<img width="1133" alt="2018-09-28 10 46 27" src="https://user-images.githubusercontent.com/2093033/46185271-d1665000-c30b-11e8-9596-d523f7c34f64.png">

**Comment by gcharita** [comment]
@starkite just update to the latest version (this is fixed since version 1.5.0)

**Comment by joseph-517** [comment]
Tks! it's work for me.
