### ISSUE TITLE
Cannot correctly parse elements with innerText and optional attributes

### ISSUE THREAD

**Issue by ewanmellor** [gcharita/XMLMapper#19]
It is impossible to correctly parse elements that use innerText and optional attributes.

Take the example in the README:

```
<food>
  <details>
    <price currency="euro">5.95</price>
  </details>
</food>
```

```
class Price: XMLMappable {
    var nodeName: String!

    var currency: String!
    var actualPrice: Float!

    required init?(map: XMLMap) {}

    func mapping(map: XMLMap) {
        currency <- map.attributes["currency"]
        actualPrice <- map.innerText
    }
}
```

In this case, if the currency is optional so the input could include either `<price currency="euro">5.95</price>` or `<price>5.95</price>`, you cannot correctly parse the latter example.  This is because the `collapseTextNodes` functionality in `XMLObjectParser` moves the `5.95` value to the parent dictionary if there are no attributes on the node.   This leaves you with no reasonable way to parse both inputs with the same mapping object.

**Comment by gcharita** [comment]
@ewanmellor for most situations the current configuration is the best.

For your case you can workaround this issue by serializing your XML using `XMLSerialization` and pass the default `ReadingOptions` except `collapseTextNodes` option:

```swift
guard let xmlData = xmlString.data(using: .utf8) else { return }
do {
    let readingOptions: XMLSerialization.ReadingOptions = [
        .trimWhiteSpace,
        .keepNodesOrder,
        .prefixedAttributes,
        .alwaysNodeName,
    ]
    let xmlObject = try XMLSerialization.xmlObject(with: xmlData, options: readingOptions)
} catch {
    print("Error: \(error.localizedDescription)")
}
```

Then you can map the XML object using `map(XMLObject:)` function of `XMLMapper`:

```swift
let object = XMLMapper<Your_XMLMappable_type>().map(XMLObject: xmlObject)
```

**Comment by ewanmellor** [comment]
Thanks @gcharita.  However, if you change the ReadingOptions, you just break the parsing elsewhere.  Now the example `calories <- map["calories"]` from the README doesn't work, because `XMLStringConvertibleTransform.transformFromXML` doesn't know that it must look at the `__text` key of the dictionary that it is given.

I think that the correct solution is to change the default parsing to not use `.collapseTextNodes`, and then change all the XMLTransformType implementations to be handle either the case where they get a bare String or a Dictionary with a `__text` key.

**Comment by gcharita** [comment]
@ewanmellor I started my day thinking that this is a good idea but it's actually not.

Using your suggestion and changing `XMLStringConvertibleTransform` means that also `XMLEnumTransform` should change. (tests are not passed) After that, mapping properties with type `Any` is not actually possible and even if we find a way to map `Any` type this will make `XMLTransformType` usage inconsistent and confusing.

Luckily, the usage of `XMLTransformType` protocol can help you even with `collapseTextNodes` enabled. (I didn't thought about this when I posted my first comment)

You can change your `Price` class to something like this:

```swift
class Price: XMLMappable {
    var nodeName: String!
    
    var currency: String?
    var actualPrice: Float!
    
    init(currency: String?, actualPrice: Float!) {
        self.currency = currency
        self.actualPrice = actualPrice
    }
    
    required init?(map: XMLMap) {}
    
    func mapping(map: XMLMap) {
        currency <- map.attributes["currency"]
        actualPrice <- map.innerText
    }
}
```

create the following custom `XMLTransformType`:

```swift
class PriceTransform: XMLTransformType {
    typealias Object = Price
    typealias XML = [String: Any]
    
    func transformFromXML(_ value: Any?) -> Object? {
        if let stringValue = value as? String, let actualPrice = Float(stringValue) {
            return Price(currency: nil, actualPrice: actualPrice)
        }
        if let xml = value as? [String: Any] {
            return Price(XML: xml)
        }
        return nil
    }
    
    func transformToXML(_ value: Object?) -> XML? {
        return value?.toXML()
    }
}
```

and use the `PriceTransform` you just created in `mapping(map:)` function like this:

```swift
price <- (map["price"], PriceTransform())
```

This will effectively map both cases in both serialization and deserialization.

**Comment by gcharita** [comment]
@ewanmellor did it worked?

**Comment by gcharita** [comment]
Closing this issue as stale. Feel free to reopen it if the suggested solution doesn't work.
