### ISSUE TITLE
XMLParserHelper xmlString, nodes with attributes only

### ISSUE THREAD

**Issue by An1metall** [gcharita/XMLMapper#2]
I think there is problem in **XMLParserHelper** **class func xmlString** in nodes with attributes only.
Suggest change string format **"<%1$@>%2$@</%1$@>"** to **"<%1$@%2$@/>"** in

`           
if !innerXML.isEmpty { return String(format: "<%1$@%2$@>%3$@</%1$@>", nodeName, attributeString, innerXML) } else { return String(format: "<%1$@>%2$@</%1$@>", nodeName, attributeString)}
`

**Comment by gcharita** [comment]
You are absolutely right! This is a bug.
The fix will be included in the next release as soon as possible.
Thank you.
