### ISSUE TITLE
Alamofire incompatability?

### ISSUE THREAD

**Issue by fizzyade** [gcharita/XMLMapper#26]
I've just cloned the alamofire git as a sibmodule in my project along with your project, when I compile I get a load of errors including "DataRequest.stringResponseSerializer" not being found and so on....

Is this only compatible with a specific maor version?

**Comment by gcharita** [comment]
Hi @fizzyade thanks for using XMLMapper.
Yes, this library is compatible with the version 4 of Alamofire (currently 4.9.1 is the latest)

I am planning to support version 5, but I am waiting to see the final official release.

**Comment by fizzyade** [comment]
hi, yeah, i realised after writing this, i switched my sub module to the 4.x branch and it all compiled nicely, have it working in my app! lovely bit of code.
