### ISSUE TITLE
Request subspec on Alamofire 4.9

### ISSUE THREAD

**Issue by mheh** [gcharita/XMLMapper#33]
I'm a hobbyist, since XMLMapper 1.6.1 is compatabile with Alamofire 5.2, I was wondering if the Request Subspec is compatible with 5.2 or oly 4.9?

EDIT: podfile has
pod 'Alamofire', '~> 5.2',
pod 'XMLMapper', '~> 1.6.1',
pod 'XMLMapper/Requests',

as well, when trying with XCode Swift package manager it does the same thing when switching to the enhancements/alamofire5 support tree. Request subspec is not optional

**Comment by gcharita** [comment]
@mheh thanks for using this library. Support for Alamofire version 5 is not completely ready yet. I need to find some time to finish it and release a new version.
If this happens, `Requests` subspec will support Alamofire 5.2

**Comment by gcharita** [comment]
Support for Alamofire 5 added with pull request #32
