### ISSUE TITLE
Recursive XML elements

### ISSUE THREAD

**Issue by aaomidi** [gcharita/XMLMapper#38]
Hi!

How would I go about handling recursive XML elements?

E.g.

```
<item>
  <id>1</id>
  <item>
    <id>2</id>
  </item>
</item>
```

**Comment by gcharita** [comment]
@aaomidi thanks for using XMLMapper.

You can use the optional strategy with a model class like this:

```swift
class Item: XMLMappable {
    var nodeName: String!
    
    var id: Int?
    var item: Item?

    required init?(map: XMLMap) {}
    
    func mapping(map: XMLMap) {
        id <- map["id"]
        item <- map["item"]
    }
}
```

**Comment by aaomidi** [comment]
Thank you!

**Comment by aaomidi** [comment]
I don't think this is working :(

Some code to demonstrate:

```
class NavPoint: XMLMappable, Identifiable {

    var nodeName: String!

    var navLabel: String!
    var contentSrc: String!
    var navPoint: NavPoint?

    required init?(map: XMLMap) { }
    
    func mapping(map: XMLMap) {
        print("start new")
        navLabel <- map["navLabel.text"]
        contentSrc <- map["content"].attributes["content.src"]
        print("start navLabel: \(navLabel!)")
        navPoint <- map["navPoint"]
        print("end navLabel: \(navLabel!)")
    }
}
```

Prints:

```
start new
start navLabel: Cover
end navLabel: Cover
start new
start navLabel: Area X: The Southern Reach Trilogy
end navLabel: Area X: The Southern Reach Trilogy
start new
start navLabel: Annihilation
end navLabel: Annihilation
start new
start navLabel: Authority
end navLabel: Authority
start new
start navLabel: Acceptance
end navLabel: Acceptance
start new
start navLabel: Area X Map
end navLabel: Area X Map
```

This is the first level nodes in the XML file.

**Comment by aaomidi** [comment]
I've taken a bit deeper of a look, and map definitely contains the values. It just never tries to construct the new one. 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1465785/108804678-f35f6d80-756b-11eb-895b-aa56725b37ac.png">

**Comment by aaomidi** [comment]
I can see it hitting: 
https://github.com/gcharita/XMLMapper/blob/master/XMLMapper/Classes/XMLMapper.swift#L66

Then failing that and hitting:
https://github.com/gcharita/XMLMapper/blob/master/XMLMapper/Classes/XMLMapper.swift#L72

Also failing that and hitting:
https://github.com/gcharita/XMLMapper/blob/master/XMLMapper/Classes/XMLMapper.swift#L77

**Comment by aaomidi** [comment]
Please ignore me, I am an idiot and this was supposed to be mapped to an array, rather than an object.
