### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by mvn-toantruong-dn** [gcharita/XMLMapper#47]
Hello,
I am an employee of Monstarlab company. I have a question about the Privacy Manifest

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest.
Does XML Mapper need to include this manifest?
Please let me know about your upcoming plans to apply the privacy manifest.

Here are some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

**Comment by gcharita** [comment]
Hello @mvn-toantruong-dn, thank you for using XMLMapper.

No, XMLMapper does not use any "required reason" API nor collects any user data. Thus, a privacy manifest file does not need to be included.
