### ISSUE TITLE
crashes most of times

### ISSUE THREAD

**Issue by agenterouser** [gcharita/XMLMapper#6]
Hi guys, 

Almost of times the app crash with random xmls on this line.
`
func addText(_ additionalText: String) { 
        if case nil = text?.append(additionalText) {
            text = additionalText
        }
}`

It throws this exception on console:
`(17940,0x70000e800000) malloc: *** error for object 0x600000862ac0: Non-aligned pointer being freed (2)
*** set a breakpoint in malloc_error_break to debug`

Could you help me? :)

**Comment by gcharita** [comment]
This is interesting. Can you provide an XML example that cause this kind of crash and the classes that you use to map it?

**Comment by gcharita** [comment]
Did you tried to use the latest version (v1.4.4) ? There is a possible fix to this issue based on #8.
If the problem persist could you please share the XML and the swift code that you use to reproduce this issue?

**Comment by gcharita** [comment]
Closing this issue as stale. Feel free to reopen it if the problem persists.
