### ISSUE TITLE
Catch exceptions

### ISSUE THREAD

**Issue by ecr24** [gcharita/XMLMapper#7]
There is any way to catch the parsing errors? I can assume sometimes a xml can't be downloaded but i can't assume the app will crash anytime the xml format is wrong.

**Comment by gcharita** [comment]
It shouldn't crash anytime the XML format is wrong. It should return nil.
Can you provide an example of XML that cause a crash and the line of code that crashes? (or anything more specific to further investigate)

**Comment by gcharita** [comment]
Closing this issue as stale. Feel free to reopen it if the problem persists.
