### ISSUE TITLE
XMLObjectParser.swift problem

### ISSUE THREAD

**Issue by An1metall** [gcharita/XMLMapper#8]
In some rare cases i have crash in XMLObjectParser.swift
![2018-03-29 13 35 45](https://user-images.githubusercontent.com/12744873/38084974-8dacf6fa-3357-11e8-9712-0901a1bac1fe.png)
I believe it have some connections with threading.
Removing private static shared XMLObjectParser and make it local constant in class func dictionary seems solves the problem.
![2018-03-29 13 40 25](https://user-images.githubusercontent.com/12744873/38085181-4fb7629e-3358-11e8-9c17-1a97b26f3165.png)

**Comment by gcharita** [comment]
You are probably right. I guess I wanted to avoid the multiple instances of the `XMLObjectParser` class. 
I will follow you suggestion, as I believe this is the best I can do right now.
Thank you.
